### ISSUE TITLE
HAR => json file is not correctly converted to YAML

### ISSUE THREAD

**Issue by Hypenate** [ahebrank/vscode-yaml2json#11]
- Downloading a HAR file via Chrome.
- Upload it to https://app.apigit.com
- Download the json swagger file
- Convert the json using the tool in VSCode

Result: not all nested items are converted to YAML
Expected result: all items are converted to YAML

**Comment by ahebrank** [comment]
Ah, OK, we [limit the depth of the YAML](https://github.com/ahebrank/vscode-yaml2json/blob/master/src/command.ts#L65) for readability. It's valid YAML, but inline.

Let me see if I can make that `6` value into a user-settable parameter.

**Comment by Hypenate** [comment]
I understand the limitation.
But it works very fluent, maybe we could increase it a bit? :D 

I could also split the json file into multiple parts.

**Comment by Hypenate** [comment]
Would it be much work, the create a setting for it?

**Comment by ahebrank** [comment]
> Would it be much work, the create a setting for it?

I don't think so, just need to remember how to do it since it's been a while.

**Comment by ahebrank** [comment]
Customizing the expanded/inline cutoff is now available in 0.06 as `yaml2json.yamlExpansionDepth` setting:

<img width="982" alt="Screenshot 2024-01-19 at 1 08 10 PM" src="https://github.com/ahebrank/vscode-yaml2json/assets/5023646/11d7e290-62bf-4cfd-a855-456efb8514aa">

If you want to expand everything, make that a really large number.
